// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbK0yDtwj1FTblYjMUIAp7gE-psYv57qw',
    appId: '1:348468239571:web:d7f39252ce06e7b7cfc826',
    messagingSenderId: '348468239571',
    projectId: 'holbegram-9dd92',
    authDomain: 'holbegram-9dd92.firebaseapp.com',
    storageBucket: 'holbegram-9dd92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY0L3CqCo0-oQC9-wfr3l1WQA3Xf2l6s0',
    appId: '1:348468239571:android:c364632ce0c8af77cfc826',
    messagingSenderId: '348468239571',
    projectId: 'holbegram-9dd92',
    storageBucket: 'holbegram-9dd92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy09-Og6CfkrRqlhSDvMV_8b8KrDoJRgg',
    appId: '1:348468239571:ios:aa8f123317e9ac9fcfc826',
    messagingSenderId: '348468239571',
    projectId: 'holbegram-9dd92',
    storageBucket: 'holbegram-9dd92.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy09-Og6CfkrRqlhSDvMV_8b8KrDoJRgg',
    appId: '1:348468239571:ios:aa8f123317e9ac9fcfc826',
    messagingSenderId: '348468239571',
    projectId: 'holbegram-9dd92',
    storageBucket: 'holbegram-9dd92.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbK0yDtwj1FTblYjMUIAp7gE-psYv57qw',
    appId: '1:348468239571:web:affe47e6258822cecfc826',
    messagingSenderId: '348468239571',
    projectId: 'holbegram-9dd92',
    authDomain: 'holbegram-9dd92.firebaseapp.com',
    storageBucket: 'holbegram-9dd92.firebasestorage.app',
  );
}
